/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.hospital.adapters.gui;
import com.mycompany.hospital.application.service.EmpleadoService;
import com.mycompany.hospital.domain.model.Empleado;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.stream.Collectors; 
/**
 *
 * @author Danie
 */
public class DialogoConsultasEmpleado extends javax.swing.JDialog {

    /**
     * Creates new form DialogoConsultasEmpleado
     */
     private final EmpleadoService empleadoService;
    private JTextArea areaResultados;

    public DialogoConsultasEmpleado(Frame owner, EmpleadoService service) {
        super(owner, "Panel de Consultas de Empleado", true);
        this.empleadoService = service;
        initUI();
    }

    private void initUI() {
        setSize(500, 400);
        setLocationRelativeTo(getParent());
        setLayout(new BorderLayout(10, 10));

        // --- Panel de Acciones ---
        JPanel panelAcciones = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelAcciones.setBorder(BorderFactory.createTitledBorder("Consultas Disponibles"));
        
        JButton btnVacaciones = new JButton("Mostrar Empleados con Vacaciones (Último Año)");
        panelAcciones.add(btnVacaciones);

        // --- Área de Resultados ---
        areaResultados = new JTextArea();
        areaResultados.setEditable(false);
        areaResultados.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollResultados = new JScrollPane(areaResultados);
        scrollResultados.setBorder(BorderFactory.createTitledBorder("Resultados"));

        add(panelAcciones, BorderLayout.NORTH);
        add(scrollResultados, BorderLayout.CENTER);

        // --- Action Listener ---
        btnVacaciones.addActionListener(e -> mostrarEmpleadosConVacaciones());
    }

    private void mostrarEmpleadosConVacaciones() {
        List<Empleado> empleados = empleadoService.listarEmpleadosConVacaciones();
        if (empleados.isEmpty()) {
            areaResultados.setText("No se encontraron empleados con vacaciones en el último año.");
            return;
        }
        
        String resultado = empleados.stream()
                .map(e -> String.format("- ID: %d, Nombre: %s, Cargo: %s", e.getId(), e.getNombre(), e.getCargo()))
                .collect(Collectors.joining("\n"));
        
        areaResultados.setText("--- Empleados con Vacaciones (Último Año) ---\n" + resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoConsultasEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoConsultasEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoConsultasEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoConsultasEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
